development:
  general:
    blog_name: RBlog Sample. Keep it simple!
    blog_email: igor.alexandrov@gmail.com
  content_menu:
    show: true
    elements: [:add_post, :posts, :comments, :users]
  posts:
    external_instruments:
      twitter:
        use: true
      delicious:
        use: true
      digg:
        use: true
    topic:
      description:
        maximum_length: 500